/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfreechart;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author mario
 */
public class jpGridBagLayout extends javax.swing.JPanel {

    /**
     * Creates new form jpGridBagLayout
     */
    
    JPanel pane = new JPanel();
    boolean shouldFill = true, shouldWeightX = true;
    public jpGridBagLayout() {
        initComponents();
        addComponentes();
        
        
    }
    private void addComponentes(){
        JButton button;
        //pane.setLayout(new GridBagLayout());
        setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        if (shouldFill) {
                        //natural height, maximum width
                        c.fill = GridBagConstraints.HORIZONTAL;
        }

        button = new JButton("Button 1");
        if (shouldWeightX) {
                           c.weightx = 0.5;
        }
        c.fill = GridBagConstraints.BOTH; // preenchimento/crescimento junto com a janela
        c.gridx = 1;   // Ordem dos componenetes adicionados da esquerda para direita
        c.gridy = 0;
        //pane.add(button, c);
        add(button, c);
        
        button = new JButton("Button 2");
        c.fill = GridBagConstraints.HORIZONTAL;
        c.weightx = 0.5; //fator de crescimento
        c.gridx = 0;
        c.gridy = 0;
        //pane.add(button, c);
        add(button, c);
        
        button = new JButton("Button 3");
        c.fill = GridBagConstraints.HORIZONTAL;
        c.weightx = 0.5;
        c.gridx = 2;
        c.gridy = 0;
        //pane.add(button, c);
        add(button, c);
        
        button = new JButton("Long-Named Button 4");
        c.fill = GridBagConstraints.BOTH;
        c.ipady = 0;      //Tamanho do componente Y (altura)
        c.weightx = 0.5;
        c.weighty = 0.5;
        c.gridwidth = 2; //número de colunas que o componente irá ocupar
        c.gridheight = 2; // número de linhas que o componente irá ocupar
        c.gridx = 0; // coluna que o item será adicionado
        c.gridy = 1; // linha que será adicionado
        //pane.add(button, c);
        add(button, c);
        
        
        button = new JButton("Button 6");
        c.fill = GridBagConstraints.BOTH;
        c.weightx = 0.5;
        c.gridx = 0;
        c.gridy = 3;
        c.ipady = 0;      //Tamanho do componente Y (altura)
        c.weightx = 0.5;
        c.weighty = 0.5;
        c.gridwidth = 1; //número de colunas que o componente irá ocupar
        c.gridheight = 1; // número de linhas que o componente irá ocupar
        
        //pane.add(button, c);
        add(button, c);
        
        button = new JButton("5");
        c.fill = GridBagConstraints.BOTH;
        c.ipady = 0;       //reset to default
        c.weighty = 1.0;   //request any extra vertical space
       // c.anchor = GridBagConstraints.PAGE_END; //bottom of space
        c.insets = new Insets(10,0,0,0);  //top padding
        c.gridx = 1;       //aligned with button 2
        c.gridwidth = 2;   //2 columns wide
        c.gridy = 4;       //third row
        //pane.add(button, c);
        add(button, c);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
