/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfreechart;

/**
 *
 * @author mario
 */
public class jpItens extends javax.swing.JPanel {

    /**
     * Creates new form jpItens
     */
    public jpItens() {
        initComponents();
    }
    public jpItens(String nome, int numero){
        initComponents();
        lblNome.setText(nome);
        lblNum.setText(numero+"");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        lblNome.setText("NOME ITEM");
        add(lblNome);

        lblNum.setText("NUMERO");
        add(lblNum);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    // End of variables declaration//GEN-END:variables
}
