/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jfreechart;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;

/**
 *
 * @author mario
 */
public class jpRaizPai extends javax.swing.JPanel {

    /**
     * Creates new form jpRaizPai
     */
    public jpRaizPai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRaiz = new javax.swing.JPanel();
        txtNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jpRaiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNum)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int num = Integer.parseInt(txtNum.getText());
            jpRaiz.setLayout(new GridLayout(0, 4));//linhas e colunas
            //jpRaiz.setLayout(new FlowLayout()); // linha
            //jpRaiz.setLayout();
            jpRaiz.removeAll();
            int x =0, y = 0;
            jpItens jp;
            for(int i = 0; i<=num; i++){
                 jp = new jpItens("item: "+i, i);
                 if(i%2==0){
                     jp.setLocation(x, y);
                     y += jp.getWidth();
                 }else{
                     jp.setLocation(x+jp.getHeight()+10, y);
                 }
                jpRaiz.add(jp);
                System.out.println("Item add: "+i);
            }
            validate();
            repaint();
            System.out.println("Quantidade de componentes: "+ jpRaiz.getComponentCount());
            
        }catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpRaiz;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
