/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.pdfControl;
import Control.PedidoControl;
import Dao.RestauranteDAO;
import Dao.UsuarioDAO;
import Model.Pedido;
import Model.Restaurante;
import Model.Usuario;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class jpHistorico extends javax.swing.JPanel {

     ArrayList<Pedido> pedidoArrayList;

    public jpHistorico() {
        inicializar();
    }
    private void inicializar(){
        initComponents();
        limparCamposPesquisa();
        pedidoArrayList = new ArrayList<Pedido>();
        pesquisarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txfDataInicio = new javax.swing.JTextField();
        try{            javax.swing.text.MaskFormatter data =               new javax.swing.text.MaskFormatter("##/##/####");        txfDataInicio = new javax.swing.JFormattedTextField(data);    }catch(Exception e){    }
        txfDatafinal = new javax.swing.JTextField();
        try{            javax.swing.text.MaskFormatter data =               new javax.swing.text.MaskFormatter("##/##/####");        txfDatafinal = new javax.swing.JFormattedTextField(data);    }catch(Exception e){    }
        jLabel10 = new javax.swing.JLabel();
        txfRestaurantePesq = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txfDescricaoPesq = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescricaoH = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListResultado = new javax.swing.JList<>();
        btnLimparH = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lblNPedido = new javax.swing.JLabel();
        lblUsuarioH = new javax.swing.JLabel();
        lblRestauranteH = new javax.swing.JLabel();
        lblDataH = new javax.swing.JLabel();
        lblQuantidadeH = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Data Início");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Data Final");

        txfDataInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDataInicio.setText("27/06/2020");
        txfDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfDataInicioFocusLost(evt);
            }
        });
        txfDataInicio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txfDataInicioInputMethodTextChanged(evt);
            }
        });

        txfDatafinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDatafinal.setText("27/06/2020");
        txfDatafinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfDatafinalFocusLost(evt);
            }
        });
        txfDatafinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDatafinalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Restaurante");

        txfRestaurantePesq.setText("Nome do Restaurante");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Descrição");

        txfDescricaoPesq.setText("Nome dos Funcionários");

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 204));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_find_replace_black_18dp.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Usuário");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Restaurante");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Quantidade");

        txaDescricaoH.setEditable(false);
        txaDescricaoH.setColumns(20);
        txaDescricaoH.setRows(5);
        jScrollPane2.setViewportView(txaDescricaoH);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Resultado");

        jListResultado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListResultado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListResultadoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListResultado);

        btnLimparH.setBackground(new java.awt.Color(204, 204, 255));
        btnLimparH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_history_black_18dp.png"))); // NOI18N
        btnLimparH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparHActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Data ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Detalhes");

        btnImprimir.setBackground(new java.awt.Color(204, 255, 204));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_print_black_18dp.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Pedido");

        lblNPedido.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblNPedido.setForeground(new java.awt.Color(0, 51, 153));
        lblNPedido.setText("nº Pedido");

        lblUsuarioH.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblUsuarioH.setForeground(new java.awt.Color(0, 51, 153));
        lblUsuarioH.setText("Nome do Usuário");

        lblRestauranteH.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblRestauranteH.setForeground(new java.awt.Color(0, 51, 153));
        lblRestauranteH.setText("nome do Restaurante");

        lblDataH.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblDataH.setForeground(new java.awt.Color(0, 51, 153));
        lblDataH.setText("29/06/2020");

        lblQuantidadeH.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblQuantidadeH.setForeground(new java.awt.Color(0, 51, 153));
        lblQuantidadeH.setText("55555");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfDatafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUsuarioH, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(lblRestauranteH, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDataH, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQuantidadeH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(lblNPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(593, 593, 593)))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txfRestaurantePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfDescricaoPesq))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(158, 158, 158)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDatafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimparH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfRestaurantePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDescricaoPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(jLabel17))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(lblUsuarioH)
                            .addComponent(lblRestauranteH)
                            .addComponent(lblDataH)
                            .addComponent(lblQuantidadeH)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(lblNPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDataInicioFocusLost
        try{
            String dia = txfDataInicio.getText().substring(0, 2);
            String mes = txfDataInicio.getText().substring(3, 5);
            String ano = txfDataInicio.getText().substring(6);

            Calendar calendar = new GregorianCalendar();
            calendar.setLenient(false);
            calendar.set(Integer.parseInt(ano), Integer.parseInt(mes)-1, Integer.parseInt(dia));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Informe uma data válida!", "Valor inválido",JOptionPane.WARNING_MESSAGE);
            txfDataInicio.setText("");
        }
    }//GEN-LAST:event_txfDataInicioFocusLost

    private void txfDataInicioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txfDataInicioInputMethodTextChanged

    }//GEN-LAST:event_txfDataInicioInputMethodTextChanged

    private void preencherDetalhesList(){
        int j = jListResultado.getSelectedIndex();
        if(j>=0){
            int i = pedidoArrayList.size()-j-1;
            lblUsuarioH.setText("" + new UsuarioDAO().PesquisarById(pedidoArrayList.get(i).getIdUsuario()).getNome());
            txaDescricaoH.setText(pedidoArrayList.get(i).getDescricao());
            lblRestauranteH.setText(""+ new RestauranteDAO().PesquisarById(pedidoArrayList.get(i).getIdRestaurante()).getNome());
            lblQuantidadeH.setText(pedidoArrayList.get(i).getQuantidade()+"");
            lblNPedido.setText(""+pedidoArrayList.get(i).getId());
            //lblDataH.setText(pedidoArrayList.get(i).getDataString());
            lblDataH.setText(pedidoArrayList.get(i).getDataHoraString());
        }
    }
    private void pesquisarPedidos(){
        String datainicio, datafim, descricao, restaurante;
        String diaI, diaF, mesI, mesF, anoI, anoF;
        int[] parametros={0,0,0,0,0};
        int[] dI = new int[3];
        int[] dF = new int[3];
        long datainiciomili=0, datafimmili=0;
        
        try{
            datainicio = txfDataInicio.getText();
            datafim = txfDatafinal.getText();
            
            if(!datainicio.equals("  /  /    ")){
                dI[0]= Integer.parseInt(datainicio.substring(0, 2));
                dI[1]= Integer.parseInt(datainicio.substring(3, 5));
                dI[2]= Integer.parseInt(datainicio.substring(6));
                Calendar c = new GregorianCalendar();
                c.set(dI[2], dI[1]-1, dI[0]);
                datainiciomili = c.getTimeInMillis();
                parametros[0]=1;
            }
            if(!datafim.equals("  /  /    ")){
                dF[0]= Integer.parseInt(datafim.substring(0, 2));
                dF[1]= Integer.parseInt(datafim.substring(3, 5));
                dF[2]= Integer.parseInt(datafim.substring(6));
                
                Calendar c = new GregorianCalendar();
                c.set(dF[2], dF[1]-1, dF[0]);
                datafimmili = c.getTimeInMillis();
                parametros[1]=1;
            }
            
            restaurante = txfRestaurantePesq.getText();
            ArrayList<Restaurante> listRestaurante= new ArrayList<Restaurante>();
            int[] idRest = new int[0];
            if(!restaurante.equals("")){
                parametros[3]=1;
                listRestaurante = new RestauranteDAO().PesquisarTodosByName(restaurante);
                idRest = new int[listRestaurante.size()];
                for(int r=0; r<listRestaurante.size(); r++){
                    idRest[r]=listRestaurante.get(r).getId();
                }
            }
            
            descricao = txfDescricaoPesq.getText();
            
            PedidoControl pedidoControl = new PedidoControl();

            Object[] retorno = pedidoControl.Pesquisar(parametros, datainiciomili, datafimmili, idRest, descricao);

            if((int)retorno[0]==1){
                pedidoArrayList = (ArrayList<Pedido>) retorno[1];
                preencherListaPedidos();
            }else{

            }

        }catch(Exception e){
        }
    }
    private void preencherListaPedidos(){
        DefaultListModel listModel = new DefaultListModel();
        int j=0;
        
        for(int i=pedidoArrayList.size()-1; i>=0; i--){
            String linha = "Pedido Nº " + pedidoArrayList.get(i).getId();
            linha = linha + ", Data: " + pedidoArrayList.get(i).getDataString();
            linha = linha +", Descricao: " + pedidoArrayList.get(i).getDescricao();
            listModel.add(j,linha);
            j++;
        }
        jListResultado.setModel(listModel);
    }
    private void limparCamposPesquisa(){
        txfDataInicio.setText("");
        txfDatafinal.setText("");
        txfRestaurantePesq.setText("");
        txfDescricaoPesq.setText("");
        DefaultListModel listModel = new DefaultListModel();
        jListResultado.setModel(listModel);
    }
    
    private void imprimirPedido(){
        int j = jListResultado.getSelectedIndex();
        if(j>=0){
            int i = pedidoArrayList.size()-j-1;
            Usuario usuario = new UsuarioDAO().PesquisarById(pedidoArrayList.get(i).getIdUsuario());
            Restaurante restaurante = new RestauranteDAO().PesquisarById(pedidoArrayList.get(i).getIdRestaurante());
            
            if(new pdfControl().CriarDocumentoPDF(pedidoArrayList.get(i), restaurante, usuario)){
                //JOptionPane.showMessageDialog(null, "Gerando arquivo para impressão...","Impressão de Requisição",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao imprimir","Impressão de Requisição",JOptionPane.ABORT);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item da lista para imprimir!", "Impressão de Requisição",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void txfDatafinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDatafinalFocusLost
        try{
            String dia = txfDatafinal.getText().substring(0, 2);
            String mes = txfDatafinal.getText().substring(3, 5);
            String ano = txfDatafinal.getText().substring(6);

            Calendar calendar = new GregorianCalendar();
            calendar.setLenient(false);
            calendar.set(Integer.parseInt(ano), Integer.parseInt(mes)-1, Integer.parseInt(dia));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Informe uma data válida!", "Valor inválido",JOptionPane.WARNING_MESSAGE);
            txfDatafinal.setText("");
        }
    }//GEN-LAST:event_txfDatafinalFocusLost

    private void txfDatafinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDatafinalActionPerformed

    }//GEN-LAST:event_txfDatafinalActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisarPedidos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jListResultadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListResultadoValueChanged
        preencherDetalhesList();
    }//GEN-LAST:event_jListResultadoValueChanged

    private void btnLimparHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparHActionPerformed
        limparCamposPesquisa();
    }//GEN-LAST:event_btnLimparHActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        imprimirPedido();
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimparH;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListResultado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDataH;
    private javax.swing.JLabel lblNPedido;
    private javax.swing.JLabel lblQuantidadeH;
    private javax.swing.JLabel lblRestauranteH;
    private javax.swing.JLabel lblUsuarioH;
    private javax.swing.JTextArea txaDescricaoH;
    private javax.swing.JTextField txfDataInicio;
    private javax.swing.JTextField txfDatafinal;
    private javax.swing.JTextField txfDescricaoPesq;
    private javax.swing.JTextField txfRestaurantePesq;
    // End of variables declaration//GEN-END:variables
}
