/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.RestauranteDAO;
import Model.Restaurante;
import java.awt.event.ContainerListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class jpRestaurante extends javax.swing.JPanel {

    private ArrayList<Restaurante> arraylistRestaurante;
    
    public jpRestaurante() {
        initComponents();
        arraylistRestaurante = new ArrayList<Restaurante>();
        limparCampos();
        preencherListRestaurante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfRestaurante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistRestaurantes = new javax.swing.JList<>();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        jLabel1.setText("ID");

        txfID.setEditable(false);
        txfID.setText("515455");

        jLabel2.setText("Restaurante");

        txfRestaurante.setText("Restaurante xyz");

        jLabel3.setText("Telefone");

        txfTelefone.setText("5555-5555 - 99999-9999");

        jLabel4.setText("Endereço");

        txfEndereco.setText("Endereço restaurante xyz");

        jLabel5.setText("Lista de Cadastrados");

        jlistRestaurantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistRestaurantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistRestaurantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistRestaurantes);

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_done_outline_black_18dp.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(204, 204, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_add_task_black_18dp.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 585, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfRestaurante)
                    .addComponent(txfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(txfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(btnNovo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCampos();
        enableCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            Restaurante r = new Restaurante();
            if(validarCampos()){
                r.setNome(txfRestaurante.getText().trim());
                r.setEndereco(txfEndereco.getText().trim());
                r.setTelefone(txfTelefone.getText().trim());
                if(txfID.getText().equals("")){
                    new RestauranteDAO().Inserir(r);
                    JOptionPane.showMessageDialog(null,"Salvo com sucesso!");
                }else{
                    r.setId(Integer.parseInt(txfID.getText()));
                    new RestauranteDAO().Alterar(r);
                    JOptionPane.showMessageDialog(null,"Alterado com sucesso!");
                }
                preencherListRestaurante();
            }else{
                JOptionPane.showMessageDialog(null,"O nome não pode estar em branco!","Campo inválido", JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            throw new RuntimeException(e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jlistRestaurantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistRestaurantesValueChanged
        preencherDetalhes();
    }//GEN-LAST:event_jlistRestaurantesValueChanged
    private boolean validarCampos(){
        if(txfRestaurante.getText().equals("")){
            return false;
        }
        return true;
    }
    private void limparCampos(){
        txfID.setText("");
        btnSalvar.setText("Inserir");
        txfRestaurante.setText("");
        txfTelefone.setText("");
        txfEndereco.setText("");
    }
    private void enableCampos(boolean status){
        txfEndereco.setEnabled(status);
        txfRestaurante.setEnabled(status);
        txfTelefone.setEnabled(status);
    }
    private void preencherDetalhes(){
        int j = jlistRestaurantes.getSelectedIndex();
        if(j>=0){
            int i = arraylistRestaurante.size()-j-1;
            txfID.setText(arraylistRestaurante.get(i).getId()+"");
            txfRestaurante.setText(arraylistRestaurante.get(i).getNome()+"");
            txfEndereco.setText(arraylistRestaurante.get(i).getEndereco()+"");
            txfTelefone.setText(arraylistRestaurante.get(i).getTelefone()+"");
            btnSalvar.setText("Alterar");
        }
    }
    private void preencherListRestaurante(){
        arraylistRestaurante = new ArrayList<Restaurante>();
        arraylistRestaurante = new RestauranteDAO().PesquisarTodos();
        
        DefaultListModel listModel = new DefaultListModel();
        int j=0;
        
        for(int i=arraylistRestaurante.size()-1; i>=0; i--){
            String linha = "ID: " + arraylistRestaurante.get(i).getId();
            linha = linha + ", Restaurante: " + arraylistRestaurante.get(i).getNome();
            linha = linha +", Telefone: " + arraylistRestaurante.get(i).getTelefone();
            linha = linha+",Endereço: "+arraylistRestaurante.get(i).getEndereco();
            listModel.add(j,linha);
            j++;
        }
        jlistRestaurantes.setModel(listModel);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistRestaurantes;
    private javax.swing.JTextField txfEndereco;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfRestaurante;
    private javax.swing.JTextField txfTelefone;
    // End of variables declaration//GEN-END:variables
}
