/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.UsuarioDAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class jpUsuario extends javax.swing.JPanel {

    /**
     * Creates new form jpUsuario
     */
    private Usuario usuario;
    
    public jpUsuario() {
        inicializar();
    }
    public jpUsuario(Usuario u){
        inicializar();
        this.usuario = u;
        txfUsuario.setText(usuario.getNome());
    }
    private void inicializar(){
        initComponents();
        limparCampos();
    }
    private void limparCampos(){
        txfUsuario.setText("");
        txfSenhaNova.setText("");
        txfSenhaAtual.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfSenhaAtual = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txfSenhaNova = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_account_box_black_18dp.png"))); // NOI18N
        jLabel1.setText("Nome");

        txfUsuario.setText("USUARIO XYZ");

        jLabel2.setText("Senha Atual");

        txfSenhaAtual.setText("jPasswordField1");

        jLabel3.setText("Senha Nova");

        txfSenhaNova.setText("jPasswordField1");

        jButton1.setForeground(new java.awt.Color(204, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baseline_done_outline_black_18dp.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txfSenhaAtual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfUsuario)
                                    .addComponent(txfSenhaNova, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SalvarUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void SalvarUsuario(){
        String senhaA, senhaN;
        
        StringBuilder sb = new StringBuilder();
        for(char a : txfSenhaAtual.getPassword()){
            sb.append(a);
        }
        senhaA = sb.toString();
        
        sb = new StringBuilder();
        for(char a : txfSenhaNova.getPassword()){
            sb.append(a);
        }
        senhaN = sb.toString().trim();
        
        
        Usuario u = this.usuario;
        if(senhaA.equals(usuario.getSenha())){
            u.setSenha(senhaN);
            new UsuarioDAO().Alterar(u);
             JOptionPane.showMessageDialog(null,"Alterado com sucesso!!","", JOptionPane.INFORMATION_MESSAGE);
        }else if(senhaA.equals("saaenovo")){
            u.setNome(txfUsuario.getText().trim());
            u.setSenha(senhaN);
            new UsuarioDAO().Inserir(u);
             JOptionPane.showMessageDialog(null,"Novo usuário inserido!!","", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"Senha Incorreta!!","", JOptionPane.WARNING_MESSAGE);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txfSenhaAtual;
    private javax.swing.JPasswordField txfSenhaNova;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
