package view;

import control.FreioManutencaoControl;
import control.VeiculoKMControl;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Auxiliar;
import model.FreioManutencao;
import model.Item;
import model.Veiculo;

/**
 *
 * @author mario
 */
public class jfFreioDetalhe extends javax.swing.JFrame {

    /**
     * Creates new form jfFreioDetalhe
     */
    private Veiculo veiculo;
    private int idRoda=0;
    private ArrayList<Item> arraylist;
    private FreioManutencao freioManutencao;
    
    public jfFreioDetalhe() {
        inicializar();
    }
    public jfFreioDetalhe(Veiculo veiculo, int idRoda){
        inicializar();
        this.veiculo = veiculo;
        this.idRoda = idRoda;
        this.freioManutencao = new FreioManutencaoControl().getFreioManutencao(veiculo.getId(), idRoda);
        preencherLabels();
    }
    
    
    
    
    private void inicializar(){
        initComponents();
        veiculo = new Veiculo();
        arraylist = new ArrayList<Item>();
        limparCampos();
    }
    private void preencherLabels(){
        Auxiliar aux = new Auxiliar();
        lblDataDiffUlt.setText(""+aux.diffDataAtualString(freioManutencao.getDataMilis()));
        lblDataUltima.setText(""+aux.getDataString(freioManutencao.getDataMilis()));
        lblIdFreio.setText(""+idRoda);
        lblKmDiffUlt.setText(""+new VeiculoKMControl().getDiffUltimoKmByID(veiculo.getId(), freioManutencao.getKm()));
        lblKmUltima.setText(""+freioManutencao.getKm());
        lblValor.setText("");
    }
    private void limparCampos(){
        lblDataDiffUlt.setText("");
        lblDataUltima.setText("");
        lblIdFreio.setText("");
        lblKmDiffUlt.setText("");
        lblKmUltima.setText("");
        lblValor.setText("");
        preencherListView();
    }

    private void preencherListView(){
        DefaultListModel listModel = new DefaultListModel();
        int j=0;
        arraylist = freioManutencao.getArraylist();
        float valor=0;
        for(int i=arraylist.size()-1; i>=0; i--){
            String linha = "Nº " + i;
            linha = linha + ", Marca: " + arraylist.get(i).getMarca();
            linha = linha +", Modelo: " + arraylist.get(i).getModelo();
            linha = linha +", Valor: " + arraylist.get(i).getValor();
            linha = linha +", Info: " + arraylist.get(i).getInfo();
            listModel.add(j,linha);
            j++;
            valor+=arraylist.get(i).getValor();
        }
        jList.setModel(listModel);
        
        lblValor.setText(new Auxiliar().StringFloatReais(valor));
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIdFreio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDataUltima = new javax.swing.JLabel();
        lblDataDiffUlt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblKmUltima = new javax.swing.JLabel();
        lblKmDiffUlt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        lblValor = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalhes do Freio");
        jLabel1.setOpaque(true);

        lblIdFreio.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblIdFreio.setForeground(new java.awt.Color(33, 150, 243));
        lblIdFreio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdFreio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pneu.png"))); // NOI18N
        lblIdFreio.setText("2");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Itens");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel13.setText("Data última troca");

        lblDataUltima.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lblDataUltima.setForeground(new java.awt.Color(33, 150, 243));
        lblDataUltima.setText("12/08/2020");

        lblDataDiffUlt.setText("10 meses");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel14.setText("Km na Última Troca");

        lblKmUltima.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lblKmUltima.setForeground(new java.awt.Color(33, 150, 243));
        lblKmUltima.setText("100.000");

        lblKmDiffUlt.setText("35.000");

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        lblValor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(33, 150, 243));
        lblValor.setText("R$ 345,21");

        btnNovo.setBackground(new java.awt.Color(255, 64, 129));
        btnNovo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maisp.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdFreio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataDiffUlt)
                            .addComponent(lblDataUltima)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(lblKmUltima)
                            .addComponent(lblKmDiffUlt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFreio)
                    .addComponent(btnNovo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataUltima)
                    .addComponent(lblKmUltima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDiffUlt)
                    .addComponent(lblKmDiffUlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        new Auxiliar().showMessage("Precisa implementar", "titulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfFreioDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfFreioDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfFreioDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfFreioDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfFreioDetalhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataDiffUlt;
    private javax.swing.JLabel lblDataUltima;
    private javax.swing.JLabel lblIdFreio;
    private javax.swing.JLabel lblKmDiffUlt;
    private javax.swing.JLabel lblKmUltima;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
