/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ItemControl;
import control.PedidoControl;
import control.VeiculoKMControl;
import control.VeiculoPreventivaControl;
import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Auxiliar;
import model.DefaultTableModelNaoEditavel;
import model.Item;
import model.Pedido;
import model.PedidoItem;
import model.Usuario;
import model.Veiculo;
import model.VeiculoPreventiva;

/**
 *
 * @author mario
 */
public class jfTrocaOleo extends javax.swing.JFrame {

    jpCustoOleo jpPai;
    Usuario usuario;
    Veiculo veiculo;
    ArrayList<Item> arraylistItens;
    ArrayList<PedidoItem> arraylistPedidoItem;
    ArrayList<Integer> arraylistKMProximo;
    ArrayList<VeiculoPreventiva> arrayListVeiculoPreventiva;
    Auxiliar aux;
    VeiculoPreventivaControl vpc;
    PedidoControl pc;
    ItemControl ic;
    VeiculoKMControl vkc;
    int[] prazos = {1000,2000, 3000, 4000, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000,50000,60000,70000,80000,90000,100000};
    int kmAtual=0;
    public jfTrocaOleo() {
        inicializar();
    }
    public jfTrocaOleo(jpCustoOleo jpPai, Usuario usuario, Veiculo veiculo){
        inicializar();
        this.jpPai = jpPai;
        this.usuario = usuario;
        this.veiculo = veiculo;
        atualizarTela();
    }
    private void inicializar(){
        initComponents();
        aux = new Auxiliar();
        vpc = new VeiculoPreventivaControl();
        pc = new PedidoControl();
        ic = new ItemControl();
        vkc = new VeiculoKMControl();
        this.usuario = new Usuario();
        this.veiculo = new Veiculo();
        arraylistPedidoItem = new ArrayList<PedidoItem>();
        arrayListVeiculoPreventiva = new ArrayList<VeiculoPreventiva>();
        arraylistKMProximo = new ArrayList<Integer>();
        preencherCBBTipo();
        preencherCBBPrazo();
    }
  
   
    public void atualizarTela(){
        try{
            atualizarInfoVeiculo(veiculo);
            atualizarTabelaItens();
            int tipoindex = cbbTipo.getSelectedIndex();
            int itemindex = cbbItem.getSelectedIndex();
            preencherCBBTipo();
            cbbTipo.setSelectedIndex(tipoindex);
            cbbItem.setSelectedIndex(itemindex);
        }catch(Exception e){
        }
    }
    private void atualizarInfoVeiculo(Veiculo v){
        lblAno.setText(v.getAno()+"");
        lblCarroceria.setText(v.getCarroceria());
        lblConfiguracao.setText(Veiculo.confLabels[v.getConfiguracao()]);
        lblInfo.setText(v.getInfo());
        lblMarca.setText(v.getMarca());
        lblModelo.setText(v.getModelo());
        lblPlaca.setText(v.getPlaca());
        lblTipo.setText(v.getTipo());
        kmAtual = vkc.getUltimoKmByIDVeiculo(v.getId());
        lblKM.setText(kmAtual+"");
        txfKm.setText(kmAtual+"");
    }
    private void preencherCBBTipo(){
        cbbTipo.removeAllItems();
        for(int i: Item.OLEOSFILTROS){
            cbbTipo.addItem(Item.TIPO_STRING[i]);
        }
       /* for(int i: Item.FILTROS){
            cbbTipo.addItem(Item.TIPO_STRING[i]);
        }*/
        for(int i: Item.OUTROS){
            cbbTipo.addItem(Item.TIPO_STRING[i]);
        }
        cbbTipo.setSelectedIndex(0);
    }
    private void preencherCBBItem(int tipo){
        cbbItem.removeAllItems();
        try{
            arraylistItens = ic.getArrayListItemByTipo(new int[]{tipo}); 
            
            for(Item item: arraylistItens){
                cbbItem.addItem(item.getMarcaModelo());
            }
        }catch(Exception e){
            
        }
    }
    private void preencherCBBPrazo(){
        cbbPrazo.removeAllItems();
        for (int i: prazos){
            cbbPrazo.addItem(i+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblConfiguracao = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCarroceria = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblKM = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbbTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbbItem = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txfMarca = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txfQtde = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txfModelo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaInfo = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txfValor = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbbPrazo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txfKm = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblPedidoTotal = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txfInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/oleo.png"))); // NOI18N
        jLabel1.setText("Troca de Óleo e Filtro");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Placa");

        lblPlaca.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPlaca.setText("DLH8657");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Tipo");

        lblTipo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTipo.setText("Carro");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("Marca");

        lblMarca.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblMarca.setText("Volkswagem");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("Modelo");

        lblModelo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblModelo.setText("GOL G4");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("Ano");

        lblAno.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAno.setText("2015");

        lblInfo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblInfo.setText("Cor vermelho");

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setText("Informação");

        lblConfiguracao.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblConfiguracao.setText("4x2");

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setText("Configuração");

        lblCarroceria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCarroceria.setText("Não se aplica");

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setText("Carroceria");

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel24.setText("KM Atual");

        lblKM.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblKM.setForeground(new java.awt.Color(33, 150, 243));
        lblKM.setText("2015");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMarca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModelo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAno)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKM)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCarroceria)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConfiguracao)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(lblKM))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblPlaca)
                        .addComponent(jLabel9)
                        .addComponent(lblTipo)
                        .addComponent(jLabel10)
                        .addComponent(lblMarca)
                        .addComponent(jLabel11)
                        .addComponent(lblModelo)
                        .addComponent(jLabel12)
                        .addComponent(lblAno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblCarroceria)
                    .addComponent(jLabel14)
                    .addComponent(lblConfiguracao)
                    .addComponent(jLabel15)
                    .addComponent(lblInfo)))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N

        jLabel16.setText("Tipo");

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTipoItemStateChanged(evt);
            }
        });

        jLabel17.setText("Item");

        cbbItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbItemItemStateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setText("Nome / Marca");

        txfMarca.setEditable(false);
        txfMarca.setText("TechFil");

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setText("Quantidade");

        txfQtde.setText("1");
        txfQtde.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txfQtdeCaretUpdate(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setText("Descrição / Modelo");

        txfModelo.setEditable(false);
        txfModelo.setText("xyz");

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setText("Informação");

        txaInfo.setEditable(false);
        txaInfo.setColumns(20);
        txaInfo.setRows(5);
        jScrollPane7.setViewportView(txaInfo);

        btnAdicionar.setBackground(new java.awt.Color(33, 150, 243));
        btnAdicionar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maisp.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 51));
        btnAtualizar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analisep.png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheirop.png"))); // NOI18N
        jLabel22.setText("Valor (unidade)");

        txfValor.setText("20,50");
        txfValor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txfValorCaretUpdate(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTotal.setText("R$ 15.000,00");

        jLabel23.setText("Prazo de Troca");

        cbbPrazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbPrazo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPrazoItemStateChanged(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setText("KM na Troca");

        txfKm.setText("1");
        txfKm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfKmFocusLost(evt);
            }
        });
        txfKm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfKmKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfModelo))
            .addComponent(jScrollPane7)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfKm, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(cbbPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(btnAdicionar))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(cbbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAtualizar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(txfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Trocados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setShowGrid(true);
        jScrollPane8.setViewportView(jTable);

        btnFinalizar.setBackground(new java.awt.Color(255, 64, 129));
        btnFinalizar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvarp.png"))); // NOI18N
        btnFinalizar.setText("Finalizar ");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/freiop.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblPedidoTotal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPedidoTotal.setText("R$ 15.000,00");

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setText("Informação do Pedido");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(txfInfo)
                .addGap(18, 18, 18)
                .addComponent(lblPedidoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnFinalizar)
                    .addComponent(lblPedidoTotal)
                    .addComponent(jLabel26)
                    .addComponent(txfInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTipoItemStateChanged
        int index = 0;
        try{
            String item = cbbTipo.getItemAt(cbbTipo.getSelectedIndex());
            for(int i = 0; i<Item.TIPO_STRING.length; i++){
                if(item.equalsIgnoreCase(Item.TIPO_STRING[i])){
                    index = Item.TIPOS_INT[i];
                }
            }
        }catch(Exception e){
            
        }finally{
            preencherCBBItem(index);
        }
    }//GEN-LAST:event_cbbTipoItemStateChanged
    private void cbbItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbItemItemStateChanged
        try{
                txfMarca.setText("");
                txfModelo.setText("");
                txfValor.setText("");
                txaInfo.setText("");
                txfQtde.setText("1");
            if(cbbItem.getSize().height>0){
                Item item = arraylistItens.get(cbbItem.getSelectedIndex());
                txfMarca.setText(item.getMarca());
                txfModelo.setText(item.getModelo());
                txfValor.setText(item.getValor()+"");
                txaInfo.setText(item.getInfo());
                
            }
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_cbbItemItemStateChanged
    private void txfQtdeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txfQtdeCaretUpdate
       float qtde =1;
       if(txfQtde.getText().trim().equalsIgnoreCase("1")){
           return;
       }
       try{
           qtde = aux.StringToFloat(txfQtde.getText());
       }catch(Exception e){
           return;
           //txfQtde.setText("1");
       }finally{
           atualizarTotal();
       } 
    }//GEN-LAST:event_txfQtdeCaretUpdate
    private void atualizarTotal(){
        float valor = 0, qtde = 1;
        try{
            valor = Float.parseFloat(txfValor.getText());
            qtde = Float.parseFloat(txfQtde.getText());
            
        }catch(Exception e){
            
        }finally{
            valor = valor * qtde;
            lblTotal.setText(""+aux.StringFloatReais(valor));
        }
    }
    private void txfValorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txfValorCaretUpdate
       float valor =0, valorAnterior =0;
       if(txfValor.getText().trim().equalsIgnoreCase("")){
           return;
       }
        try{ 
           if(cbbItem.getSize().height>0){
               valorAnterior = arraylistItens.get(cbbItem.getSelectedIndex()).getValor();
           }
          valor = aux.StringToFloat(txfValor.getText());
       }catch(Exception e){
          txfValor.setText(valorAnterior+"");
       }finally{
           atualizarTotal();
       } 
    }//GEN-LAST:event_txfValorCaretUpdate
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        PedidoItem pedidoItem = new PedidoItem();
        try{
            pedidoItem.setQuantidade(Float.parseFloat(txfQtde.getText()));
            pedidoItem.setValor(Float.parseFloat(txfValor.getText()));
            if(cbbItem.getItemCount()>0){
                pedidoItem.setIdItem(arraylistItens.get(cbbItem.getSelectedIndex()).getId());
            }
            arraylistPedidoItem.add(pedidoItem);
            arraylistKMProximo.add(prazos[cbbPrazo.getSelectedIndex()]);
        }catch(Exception e){
            
        }finally{
            atualizarTabelaItens();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i = 0;
        try{
            i = jTable.getSelectedRow();
            arraylistPedidoItem.remove(i);
            arraylistKMProximo.remove(i);
        }catch(Exception e){
            
        }finally{
            atualizarTabelaItens();
        }  
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void PedidoGeradoComSucesso(){
        try{
            aux.showMessageInformacao("Pedido Salvo com Sucesso.", "Troca de Óleo e Filtro");
            arraylistPedidoItem.clear();
            atualizarTela();
            jpPai.atualizarTela();
        }catch (Exception e){
            
        }
    }
    private boolean validarKm(String km){
        try{
            int kmTroca = Integer.parseInt(km);
            if(kmTroca<=kmAtual){
                return  true;
            }else{
                aux.showMessageInformacao("Km maior que o último Km registrado. Atualize Km do Veiculo para continuar!", "Validação de valor");
            }
            
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpTrocaOleo.validarKM");
        }
        return false;
    }
    
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try{
            if(arraylistPedidoItem.size()>0){
                if(preencherVeiculoPreventivaFutura()){
                   Pedido pedido = new Pedido();
                   pedido.setId_veiculo(veiculo.getId());
                   pedido.setDatamilis(aux.getDataMilisAtual());
                   pedido.setKm(Integer.parseInt(txfKm.getText()));
                   pedido.setArraylist(arraylistPedidoItem);
                   pedido.setTipo(Pedido.OLEOFILTRO);
                   pedido.setInfo(txfInfo.getText());

                   PedidoControl pc = new PedidoControl();
                   if(pc.Inserir(pedido)){
                       pedido.setId(pc.getUltimoPedidoByIdVeiculo(veiculo.getId()).getId());
                       vpc.atualizarPreventivaByPedido(pedido, arrayListVeiculoPreventiva);
                       PedidoGeradoComSucesso();
                   }
                }
            }else{
                aux.showMessageInformacao("Acrescente pelo menos um item ao pedido", "Lista vazia");
            }
        }catch(Exception e){      }
    }//GEN-LAST:event_btnFinalizarActionPerformed
    private boolean preencherVeiculoPreventivaFutura(){//checar se os valores da tabela (km e data) está corretos e preencer o arraylist.
        VeiculoPreventiva vp;
        arrayListVeiculoPreventiva.clear();
        try{
            for(int i=0; i<jTable.getRowCount();i++){

                String km = jTable.getModel().getValueAt(i, 7).toString();
                //String data = jTable.getModel().getValueAt(i, 7).toString();
                vp = new VeiculoPreventiva();
                //vp.setData(aux.dataStringLong(data));
                vp.setId_veiculo(veiculo.getId());
                vp.setTipo(ic.getItemByID(arraylistPedidoItem.get(i).getIdItem()).getTipo());
                vp.setKmProx(Integer.parseInt(km));
                vp.setKm(kmAtual);
                arrayListVeiculoPreventiva.add(vp);
            }
        }catch(Exception e){
            aux.showMessageWarning(e.getMessage(), "Metodo PreencherVeiculoPreventiva");
            return false;
        }
        return true;
    }
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try{
            JDialog jd = new JDialog();
            
            jpCadastroItensDiversos jp = new jpCadastroItensDiversos((Object)this, Pedido.OLEOFILTRO, arraylistItens.get(cbbItem.getSelectedIndex()));
            jd.setSize(700, 500);
            jd.setContentPane(jp);
            jd.setModal(true);
            jd.setLocationRelativeTo(null);
            
            
            jd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            //Definir tamanho da janela.. verificar também o construtor da classe acima.. não está selecionado o item passado..
            jd.setVisible(true);
            
        }catch(Exception e){}
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cbbPrazoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPrazoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPrazoItemStateChanged

    private void txfKmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfKmFocusLost
        if(!validarKm(txfKm.getText())){
            txfKm.setText(kmAtual+"");
        }
    }//GEN-LAST:event_txfKmFocusLost

    private void txfKmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfKmKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            if(!validarKm(txfKm.getText())){
                txfKm.setText(kmAtual+"");
            }
        }
    }//GEN-LAST:event_txfKmKeyPressed
    private void atualizarTabelaItens(){
        DefaultTableModel tableModel = new DefaultTableModelNaoEditavel();
        tableModel.addColumn("Nº");
        tableModel.addColumn("Tipo");
        tableModel.addColumn("Marca");
        tableModel.addColumn("Modelo");
        tableModel.addColumn("Valor (Unitário)");
        tableModel.addColumn("Quantidade");
        tableModel.addColumn("Valor Total");
        tableModel.addColumn("KM Próxima Troca");
       
        try{
            Auxiliar aux = new Auxiliar();
            Object[] linha = new Object[8];
            Item item = new Item();
            ItemControl ic = new ItemControl();
            int km = Integer.parseInt(txfKm.getText());
            float pedidoTotal = 0;
            for(int i = 0; i<arraylistPedidoItem.size(); i++){
                linha[0]= i+1;
                item = ic.getItemByID(arraylistPedidoItem.get(i).getIdItem());
                linha[1]= Item.TIPO_STRING[item.getTipo()];
                linha[2]=item.getMarca();
                linha[3]=item.getModelo();
                linha[4]=aux.StringFloatReais(arraylistPedidoItem.get(i).getValor());
                linha[5]=arraylistPedidoItem.get(i).getQuantidade();
                linha[6]=arraylistPedidoItem.get(i).getValorTotal();
                linha[7]= (km + arraylistKMProximo.get(i));
                tableModel.addRow(linha);
                pedidoTotal += arraylistPedidoItem.get(i).getValorTotal();
            }
            lblPedidoTotal.setText(aux.StringFloatReais(pedidoTotal));
        }catch (Exception e){
            aux.showMessageWarning("Verificar metodo preenchertableProxima jpTrocaOleo", "Inesperado");
        }finally{
            jTable.setModel(tableModel);
            jTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTrocaOleo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> cbbItem;
    private javax.swing.JComboBox<String> cbbPrazo;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCarroceria;
    private javax.swing.JLabel lblConfiguracao;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKM;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPedidoTotal;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea txaInfo;
    private javax.swing.JTextField txfInfo;
    private javax.swing.JTextField txfKm;
    private javax.swing.JTextField txfMarca;
    private javax.swing.JTextField txfModelo;
    private javax.swing.JTextField txfQtde;
    private javax.swing.JTextField txfValor;
    // End of variables declaration//GEN-END:variables
}
