package view;

import control.UsuarioControl;
import model.Auxiliar;
import model.Usuario;
import model.UsuarioLogin;

/**
 *
 * @author mario
 */
public class jpAlterarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form jpAlterarUsuario
     */
    Usuario usuario;
    UsuarioControl uCtrol;
    Auxiliar aux;
    private static String SENHA_DIVERGE = "As senhas novas divergem.";
    private static String SENHA_ALTERADA = "Alterado com sucesso.";
    public jpAlterarUsuario(){
        inicializar();
    }
    
    public jpAlterarUsuario(Usuario usuario) {
        inicializar();
        this.usuario = usuario;
        lblUsuario.setText(usuario.getNome());
    }
    private void inicializar(){
        initComponents();
        usuario = new Usuario();
        uCtrol = new UsuarioControl();
        aux = new Auxiliar();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfSenhaAtual = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txfSenhaNova = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txfConfirmaSenha = new javax.swing.JPasswordField();
        lblInfo = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Usuário");
        jLabel1.setOpaque(true);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Usuário Logado");
        jPanel1.add(jLabel2);

        lblUsuario.setText("MARIO");
        jPanel1.add(lblUsuario);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Informe a senha atual");
        jPanel1.add(jLabel4);
        jPanel1.add(txfSenhaAtual);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Nova Senha");
        jPanel1.add(jLabel5);
        jPanel1.add(txfSenhaNova);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Confirmação");
        jPanel1.add(jLabel6);
        jPanel1.add(txfConfirmaSenha);

        lblInfo.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 64, 129));
        jPanel1.add(lblInfo);

        btnAlterar.setBackground(new java.awt.Color(33, 150, 243));
        btnAlterar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try{
            Object[] retorno;
            StringBuilder sb = new StringBuilder();
            for(char a: txfSenhaNova.getPassword()){
                sb.append(a);
            }
            String senhaNova = sb.toString();
            sb = new StringBuilder();
            for(char a: txfSenhaAtual.getPassword()){
                sb.append(a);
            }
            String senhaAtual = sb.toString();
            sb = new StringBuilder();
            for(char a: txfConfirmaSenha.getPassword()){
                sb.append(a);
            }
            String senhaConfirma = sb.toString();
            
            //if(txfSenhaNova.getPassword().toString().equalsIgnoreCase(txfConfirmaSenha.getPassword().toString()) && txfSenhaNova.getPassword().length>=UsuarioLogin.TAMANHO_MININO_SENHA){
            if(senhaNova.equals(senhaConfirma)){  
                retorno = uCtrol.alterarSenha(usuario, txfSenhaAtual.getPassword(), txfConfirmaSenha.getPassword());
                lblInfo.setText((String)retorno[UsuarioControl.INFO]);
            }else{
                aux.showMessageWarning(SENHA_DIVERGE, "Confirmação da senha nova");
                lblInfo.setText(SENHA_DIVERGE);
            }
            
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAlterarUsuario.btnAlterarActionPerformed");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txfConfirmaSenha;
    private javax.swing.JPasswordField txfSenhaAtual;
    private javax.swing.JPasswordField txfSenhaNova;
    // End of variables declaration//GEN-END:variables
}
