package view;

import control.AvisoControl;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Auxiliar;
import model.Aviso;
import model.DefaultTableModelNaoEditavel;
import model.Veiculo;

/**
 *
 * @author mario
 */
public class jpAvisos extends javax.swing.JPanel {

    Veiculo veiculo;
    Auxiliar aux;
    ArrayList<Aviso> arrayList;
    AvisoControl ac;
    public jpAvisos() {
        inicializar();
    }
    public jpAvisos(Veiculo veiculo){
        inicializar();
        this.veiculo = veiculo;
        txfPlaca.setText(veiculo.getPlaca());
        atualizarTela();
    }
    private void inicializar(){
        initComponents();
        //veiculo = new Veiculo();
        aux = new Auxiliar();
        arrayList = new ArrayList<>();
        ac = new AvisoControl();
        jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                  if(e.getValueIsAdjusting())
                      return;
                 preencherSelectedTable();
            }
        });
    }
    private void atualizarTela(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                preencherTabela();
            }
        }).start();
        
    }
    private void preencherArrayList(){
        try{
            arrayList.clear();
            if(chAtivos.isSelected()){
                arrayList.addAll(ac.getArrayListAtivosByIdVeiculo(veiculo.getId()));
            }
            if(chInativos.isSelected()){
                arrayList.addAll(ac.getArrayListInativosByIdVeiculo(veiculo.getId()));
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAvisos.preencherArrayList");
        }
    }
    private void preencherAvisoSelecionado(Aviso aviso){
        try{
            lblData.setText(aux.getDataString(aviso.getDatamilis()));
            lblId.setText(aviso.getId()+"");
            lblTitulo.setText(aviso.getTitulo());
            txaMensagem.setText(aviso.getMensagem());
            lblStatus.setText((aviso.isAtivo()?"Ativo": "Inativo"));
            if(aviso.isAtivo()){
                btnExcluirInativar.setText("Inativar");
            }else{
                 btnExcluirInativar.setText("Excluir");
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAvisos.preencherAvisoSelecionado");
        }
    }
    private void preencherSelectedTable(){
        try{
            int i = jTable.getSelectedRow();
            if(i>=0 && arrayList.size()>0){
                preencherAvisoSelecionado(arrayList.get(arrayList.size()-i-1));
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAvisos.preencherSelectedTable");
        }
    }
    private void preencherTabela(){
        DefaultTableModel model = new DefaultTableModelNaoEditavel();
        try{
            model.addColumn("N");
            model.addColumn("ID");
            model.addColumn("Data");
            model.addColumn("Título");
            model.addColumn("Mensagem");
            model.addColumn("Status");
            
            preencherArrayList();
            
            Object[] linha = new Object[6];
            for(int i = arrayList.size()-1; i >=0; i--){
                linha[0]= (i+1);
                linha[1]= arrayList.get(i).getId();
                linha[2]= aux.getDataString(arrayList.get(i).getDatamilis());
                linha[3]= arrayList.get(i).getTitulo();
                linha[4]= arrayList.get(i).getMensagem();
                linha[5]= (arrayList.get(i).isAtivo()? "Ativo":"Inativo");
                model.addRow(linha);
            }
            
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAvisos.preencherTabela");
        }finally{
            jTable.setModel(model);
             jTable.getColumnModel().getColumn(0).setMaxWidth(35);
             jTable.getColumnModel().getColumn(1).setMaxWidth(35);
             jTable.getColumnModel().getColumn(2).setMaxWidth(70);
             jTable.getColumnModel().getColumn(5).setMaxWidth(70);
        
            
            lblNAtivos.setText(ac.getNAtivosByIdVeiculo(veiculo.getId())+"");
            if(arrayList.size()>0){
                jTable.addRowSelectionInterval(0, 0);
            }
        }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblNAtivos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        chAtivos = new javax.swing.JCheckBox();
        chInativos = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnExcluirInativar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMensagem = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Avisos");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Placa ");

        txfPlaca.setEditable(false);
        txfPlaca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txfPlaca.setText("DLH8657");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("Ativos");

        lblNAtivos.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblNAtivos.setForeground(new java.awt.Color(255, 64, 129));
        lblNAtivos.setText("15");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avisos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(127, 127, 127))); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        chAtivos.setSelected(true);
        chAtivos.setText("Ativos");
        chAtivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chAtivosItemStateChanged(evt);
            }
        });

        chInativos.setText("Inativos");
        chInativos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chInativosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chAtivos)
                .addGap(18, 18, 18)
                .addComponent(chInativos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chAtivos)
                    .addComponent(chInativos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(127, 127, 127))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Data");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Titulo");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Mensagem");

        lblId.setText("1550");

        lblData.setText("16/02/2025 15:45");

        lblTitulo.setText("titulo");

        lblStatus.setText("Ativo");

        btnExcluirInativar.setBackground(new java.awt.Color(255, 64, 129));
        btnExcluirInativar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnExcluirInativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvarp.png"))); // NOI18N
        btnExcluirInativar.setText("Excluir");
        btnExcluirInativar.setMaximumSize(new java.awt.Dimension(107, 27));
        btnExcluirInativar.setMinimumSize(new java.awt.Dimension(107, 27));
        btnExcluirInativar.setPreferredSize(new java.awt.Dimension(107, 27));
        btnExcluirInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirInativarActionPerformed(evt);
            }
        });

        txaMensagem.setEditable(false);
        txaMensagem.setColumns(20);
        txaMensagem.setRows(5);
        jScrollPane2.setViewportView(txaMensagem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(btnExcluirInativar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblId)
                    .addComponent(lblData)
                    .addComponent(lblStatus)
                    .addComponent(btnExcluirInativar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAdicionar.setBackground(new java.awt.Color(33, 150, 243));
        btnAdicionar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maisp.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txfPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNAtivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblNAtivos)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        if(!jfPrincipal.isUserOperaOrAdmin()){
            aux.showMessagemSemPermissao();
            return;
        }
        try{
             String titulo = "", mensagem = "";
             titulo = aux.InputText("Informe o Título para representar o Aviso");
             if(titulo.equalsIgnoreCase("")){
                 return;
             }
             mensagem = aux.InputText("Informe a mensagem do Aviso");
             if(mensagem.equalsIgnoreCase("")){
                 return;
             }
             Aviso aviso = new Aviso();
             aviso.setTitulo(titulo);
             aviso.setMensagem(mensagem);
             aviso.setDatamilis(aux.getDataMilisAtual());
             aviso.setAtivo(true);
             aviso.setIdveiculo(veiculo.getId());

             if(aux.ConfirmarValor(titulo, mensagem+"\nConfirma a inclusão do aviso?")){
                 ac.inserir(aviso);
                 atualizarTela();
             }
         }catch(Exception e){
             aux.RegistrarLog(e.getMessage(), "jpAvisos.btnAdicionarActionPerfomed");
         }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirInativarActionPerformed
        if(!jfPrincipal.isUserOperaOrAdmin()){
            aux.showMessagemSemPermissao();
            return;
        }
        try{
            if(jTable.getSelectedRow()>=0 && arrayList.size()>=0){
             int index = arrayList.size() - 1 - jTable.getSelectedRow();
            if(ac.excluirInativar(arrayList.get(index))){ // passa o aviso
                if(arrayList.get(index).isAtivo()){ //se ele já era inativo exclui e atualiza tabela
                    lblData.setText("Inativo");
                    arrayList.get(index).setAtivo(false);
                }else{
                    preencherTabela();
                }
            }
        }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpAvisos.btnExcluirInativarActionPermormed");
        }
    }//GEN-LAST:event_btnExcluirInativarActionPerformed

    private void jTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyTyped
        preencherSelectedTable();
    }//GEN-LAST:event_jTableKeyTyped

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        preencherSelectedTable();
    }//GEN-LAST:event_jTableMouseClicked

    private void chAtivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chAtivosItemStateChanged
        preencherTabela();
    }//GEN-LAST:event_chAtivosItemStateChanged

    private void chInativosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chInativosItemStateChanged
       preencherTabela();
    }//GEN-LAST:event_chInativosItemStateChanged

    private void jTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyReleased
        preencherSelectedTable();
    }//GEN-LAST:event_jTableKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluirInativar;
    private javax.swing.JCheckBox chAtivos;
    private javax.swing.JCheckBox chInativos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNAtivos;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txaMensagem;
    private javax.swing.JTextField txfPlaca;
    // End of variables declaration//GEN-END:variables
}
