/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.UsuarioControl;
import control.VeiculoControl;
import java.awt.CardLayout;
import java.awt.Dimension;
import model.Usuario;
import model.Veiculo;

/**
 *
 * @author mario
 */
public class jpDetalheVeiculo extends javax.swing.JPanel {
    
    private static final String CL_ANALISE = "CL1";
    private static final String CL_ABASTECIMENTO = "CL2";
    private static final String CL_QUILOMETRAGEM = "CL3";
    private static final String CL_PNEU = "CL4";
    private static final String CL_OLEO = "CL5";
   // private static final String CL_FILTRO = "CL6";
   // private static final String CL_FREIO = "CL7";
    private static final String CL_AVISO = "CL8";
    private static final String CL_MANUTENCAO = "CL9";
    private Veiculo veiculo;
    private Usuario usuario;
    private String CL_ATUAL = CL_ANALISE;
    private jfPrincipal jfp;
    
    public jpDetalheVeiculo() {
        initComponents();
        inicializar();
    }
    public jpDetalheVeiculo(jfPrincipal jfp, Veiculo veiculo, Usuario usuario){
        inicializar();
        this.veiculo = veiculo;
        this.usuario = usuario;
        this.jfp = jfp;
        txtPlacaPrincipal.setText(veiculo.getPlaca());
        adicionarJPanels(CL_ANALISE);
    }
    private void Teste(){
        this.usuario = new UsuarioControl().getUsuarioById(1);
        this.veiculo = new VeiculoControl().getVeiculoByPlaca("um");
    }
    private void inicializar(){
        this.veiculo = new Veiculo();
        this.usuario = new Usuario();
        jfp = new jfPrincipal();
        initComponents();
        atualizarTamanhoBotoes();
        //adicionarJPanels();
    }
    
    private void adicionarJPanels(String nomeCard){//verificar os demais construtores para passagem de veiculo e usuario
        try{
            
            final String card = nomeCard;
            jpCoringa.removeAll();

            switch (card){
                case CL_ANALISE:
                    jpCoringa.add(CL_ANALISE, new jpCustoAtual(veiculo));
                    break;
                case CL_QUILOMETRAGEM:
                    jpCoringa.add(CL_QUILOMETRAGEM,new jpKM(veiculo, usuario));
                    break;
                case CL_ABASTECIMENTO:
                    jpCoringa.add(CL_ABASTECIMENTO,new jpCustoCombustivel(usuario, veiculo));
                    break;
                case CL_PNEU:
                    jpCoringa.add(CL_PNEU, new jpCustoPneu(veiculo));
                    break;
               /*case CL_FREIO:
                    jpCoringa.add(CL_FREIO, new jpFreio());
                    break;
                */case CL_OLEO:
                    jpCoringa.add(CL_OLEO, new jpCustoOleo(veiculo, usuario));
                    break;
                case CL_MANUTENCAO:
                    jpCoringa.add(CL_MANUTENCAO, new jpCustoManutencao(usuario, veiculo));
                    break;
            }
            jpCoringa.add(CL_ANALISE, new jpCustoAtual(veiculo));
        }catch (Exception e){
            throw new RuntimeException();
        }
    }
    
    private void TrocarPanelCoringa(String nomeCard){
        try{
            
            adicionarJPanels(nomeCard); //implementar um método para atualizar a tela automaticamente
            CL_ATUAL = nomeCard;
            CardLayout cl = (CardLayout) jpCoringa.getLayout();
            cl.show(jpCoringa, nomeCard);  
            atualizarTamanhoBotoes();
            
            
        }catch(Exception e){
            throw new RuntimeException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlacaPrincipal = new javax.swing.JTextField();
        jpBotoes = new javax.swing.JPanel();
        btnQuilometragem = new javax.swing.JLabel();
        btnManutencao = new javax.swing.JLabel();
        btnPneus = new javax.swing.JLabel();
        btnOleo = new javax.swing.JLabel();
        btnFreios = new javax.swing.JLabel();
        btnAnaliseCustos = new javax.swing.JLabel();
        btnAvisos = new javax.swing.JLabel();
        btnAbastecimento = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        jpCoringa = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Placa");

        txtPlacaPrincipal.setText("DLH 8655");

        jpBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpBotoes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpBotoesComponentResized(evt);
            }
        });

        btnQuilometragem.setBackground(new java.awt.Color(51, 51, 51));
        btnQuilometragem.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnQuilometragem.setForeground(new java.awt.Color(255, 255, 255));
        btnQuilometragem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuilometragem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/quilometragemB.png"))); // NOI18N
        btnQuilometragem.setText("Quilometragem");
        btnQuilometragem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuilometragem.setOpaque(true);
        btnQuilometragem.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnQuilometragem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuilometragemMouseClicked(evt);
            }
        });

        btnManutencao.setBackground(new java.awt.Color(180, 180, 180));
        btnManutencao.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnManutencao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btnManutencao.setText("Manutenção");
        btnManutencao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManutencao.setOpaque(true);
        btnManutencao.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnManutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManutencaoMouseClicked(evt);
            }
        });

        btnPneus.setBackground(new java.awt.Color(204, 204, 204));
        btnPneus.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnPneus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPneus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pneu.png"))); // NOI18N
        btnPneus.setText("Pneus");
        btnPneus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPneus.setOpaque(true);
        btnPneus.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPneus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPneusMouseClicked(evt);
            }
        });

        btnOleo.setBackground(new java.awt.Color(153, 153, 153));
        btnOleo.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnOleo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/oleo.png"))); // NOI18N
        btnOleo.setText("Óleo e Filtro");
        btnOleo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOleo.setOpaque(true);
        btnOleo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnOleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOleoMouseClicked(evt);
            }
        });

        btnFreios.setBackground(new java.awt.Color(230, 230, 230));
        btnFreios.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnFreios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFreios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/freio.png"))); // NOI18N
        btnFreios.setText("Freios");
        btnFreios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFreios.setOpaque(true);
        btnFreios.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnFreios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFreiosMouseClicked(evt);
            }
        });

        btnAnaliseCustos.setBackground(new java.awt.Color(0, 0, 0));
        btnAnaliseCustos.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnAnaliseCustos.setForeground(new java.awt.Color(255, 255, 255));
        btnAnaliseCustos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnaliseCustos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analiseB.png"))); // NOI18N
        btnAnaliseCustos.setText("Análise de Custos");
        btnAnaliseCustos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnaliseCustos.setOpaque(true);
        btnAnaliseCustos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAnaliseCustos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnaliseCustosMouseClicked(evt);
            }
        });

        btnAvisos.setBackground(new java.awt.Color(255, 255, 255));
        btnAvisos.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnAvisos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAvisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tarefaspendentes.png"))); // NOI18N
        btnAvisos.setText("Avisos/Notificações");
        btnAvisos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAvisos.setOpaque(true);
        btnAvisos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnAbastecimento.setBackground(new java.awt.Color(102, 102, 102));
        btnAbastecimento.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        btnAbastecimento.setForeground(new java.awt.Color(255, 255, 255));
        btnAbastecimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAbastecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/abastecimentoB.png"))); // NOI18N
        btnAbastecimento.setText("Abastecimento");
        btnAbastecimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbastecimento.setOpaque(true);
        btnAbastecimento.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAbastecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbastecimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnaliseCustos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(btnQuilometragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnAbastecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManutencao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(btnPneus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFreios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFreios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnaliseCustos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManutencao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuilometragem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPneus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOleo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbastecimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        btnProcurar.setBackground(new java.awt.Color(255, 64, 129));
        btnProcurar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnProcurar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pesquisar.png"))); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        btnDetalhes.setBackground(new java.awt.Color(33, 150, 243));
        btnDetalhes.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        btnDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analisep.png"))); // NOI18N
        btnDetalhes.setText("Cadastro");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTopoLayout = new javax.swing.GroupLayout(jpTopo);
        jpTopo.setLayout(jpTopoLayout);
        jpTopoLayout.setHorizontalGroup(
            jpTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPlacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalhes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTopoLayout.createSequentialGroup()
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jpTopoLayout.setVerticalGroup(
            jpTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar)
                    .addComponent(btnDetalhes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(367, 367, 367))
        );

        jpCoringa.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCoringa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCoringa, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuilometragemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuilometragemMouseClicked
        TrocarPanelCoringa(CL_QUILOMETRAGEM);
    }//GEN-LAST:event_btnQuilometragemMouseClicked

    private void btnPneusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPneusMouseClicked
        TrocarPanelCoringa(CL_PNEU);
    }//GEN-LAST:event_btnPneusMouseClicked

    private void btnOleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOleoMouseClicked
        TrocarPanelCoringa(CL_OLEO);
    }//GEN-LAST:event_btnOleoMouseClicked

    private void btnFreiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFreiosMouseClicked
        //TrocarPanelCoringa(CL_FREIO);
    }//GEN-LAST:event_btnFreiosMouseClicked

    private void btnAnaliseCustosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnaliseCustosMouseClicked
        // TODO add your handling code here:
        TrocarPanelCoringa(CL_ANALISE);
    }//GEN-LAST:event_btnAnaliseCustosMouseClicked

    private void btnAbastecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbastecimentoMouseClicked
        TrocarPanelCoringa(CL_ABASTECIMENTO);
    }//GEN-LAST:event_btnAbastecimentoMouseClicked

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        PesquisarPlaca();
    }//GEN-LAST:event_btnProcurarActionPerformed
    private void atualizarTamanhoBotoes(){
        try{
            int x, y;
            int largura = this.getWidth();
            int altura = 85;
            jpBotoes.setSize(largura, altura+15);
            jpBotoes.setPreferredSize(new Dimension(largura, altura+15));
            //largura = largura / 6; //sem o botão de pneu
            largura = largura / 7;

            x = btnAnaliseCustos.getX()-2;
            y = btnAnaliseCustos.getY()-2;

            btnAnaliseCustos.setLocation(x, y);
            x +=largura;
            btnQuilometragem.setLocation(x, y);
            x +=largura;
            btnAbastecimento.setLocation(x, y);
            x +=largura;
            btnOleo.setLocation(x, y);
            x +=largura;
            btnManutencao.setLocation(x, y);
            x +=largura;
            btnPneus.setLocation(x, y);
            x +=largura;
            //btnFreios.setLocation(x, y);
            //x +=largura;
            btnAvisos.setLocation(x, y);

            btnAnaliseCustos.setSize(largura, altura);
            btnAnaliseCustos.setPreferredSize(new Dimension(largura, altura));
            btnQuilometragem.setSize(largura, altura);
            btnQuilometragem.setPreferredSize(new Dimension(largura, altura));
            btnAbastecimento.setSize(largura,altura);
            btnAbastecimento.setPreferredSize(new Dimension(largura, altura));
            btnManutencao.setSize(largura,altura);
            btnManutencao.setPreferredSize(new Dimension(largura, altura));
            btnOleo.setSize(largura, altura);
            btnOleo.setPreferredSize(new Dimension(largura, altura));
            
            btnPneus.setSize(largura, altura);
            btnPneus.setPreferredSize(new Dimension(largura, altura));
            /*btnFreios.setSize(largura, altura);
            btnFreios.setPreferredSize(new Dimension(largura, altura));
            */btnAvisos.setSize(largura, altura);
            btnAvisos.setPreferredSize(new Dimension(largura, altura));

        }catch(Exception e){
            throw new RuntimeException();
        }
        
    }
    private void jpBotoesComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpBotoesComponentResized
        atualizarTamanhoBotoes();
    }//GEN-LAST:event_jpBotoesComponentResized

    private void btnManutencaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManutencaoMouseClicked
        TrocarPanelCoringa(CL_MANUTENCAO);
    }//GEN-LAST:event_btnManutencaoMouseClicked

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        if(veiculo.getId()!=0){
            jfp.AtualizarContentPane(new jpCadastroVeiculo(veiculo));
        }

    }//GEN-LAST:event_btnDetalhesActionPerformed
    private void PesquisarPlaca(){
        try{
            Veiculo v = new VeiculoControl().getVeiculoByPlaca(txtPlacaPrincipal.getText());
            if(v.getId()!=0){
                this.veiculo = v;
                txtPlacaPrincipal.setText(this.veiculo.getPlaca());
                adicionarJPanels(CL_ATUAL);
            }
        }catch (Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbastecimento;
    private javax.swing.JLabel btnAnaliseCustos;
    private javax.swing.JLabel btnAvisos;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JLabel btnFreios;
    private javax.swing.JLabel btnManutencao;
    private javax.swing.JLabel btnOleo;
    private javax.swing.JLabel btnPneus;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel btnQuilometragem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCoringa;
    private javax.swing.JPanel jpTopo;
    private javax.swing.JTextField txtPlacaPrincipal;
    // End of variables declaration//GEN-END:variables
}
