package view;

import control.UsuarioControl;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Auxiliar;
import model.DefaultTableModelNaoEditavel;
import model.Usuario;
import model.UsuarioLogin;

/**
 *
 * @author mario
 */
public class jpGerenciarUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form jpAlterarUsuario
     */
    Usuario usuario, usuarioSelecionado;
    UsuarioControl uCtrol;
    Auxiliar aux;
    
    ArrayList<Usuario> arrayList;
    
    private static String SENHA_DIVERGE = "As senhas novas divergem.";
    private static String SENHA_ALTERADA = "Alterado com sucesso.";
    private static String informacao;
    public jpGerenciarUsuarios(){
        inicializar();
    }
    
    public jpGerenciarUsuarios(Usuario usuario) {
        inicializar();
        this.usuario = usuario;
        preencherTabela();
    }
    private void inicializar(){
        initComponents();
        usuario = new Usuario();
        usuarioSelecionado = new Usuario();
        uCtrol = new UsuarioControl();
        aux = new Auxiliar();
        arrayList = new ArrayList<Usuario>();
        lblInfo.setVisible(false);
        preencherCbbNiveis();
        jTable.getSelectionModel().addListSelectionListener((e) -> {
        preencherSelectedTable();
        });
    }
   
    private void preencherCbbNiveis(){
        try{
            cbbNivel.removeAllItems();
            cbbNivelNovo.removeAllItems();
            for(String tipo: Usuario.TIPOS){
                cbbNivel.addItem(tipo);
                cbbNivelNovo.addItem(tipo);
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.preencherCBBNiveis");
        }
    }
    private void preencherArrayList(){
        try{
            arrayList = uCtrol.pesquisarTodosUsuarios(ckAdmin.isSelected(),ckAdmin.isSelected(),ckAdmin.isSelected());
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.preencherArrayList");
        }
    }
    private void preencherSelectedTable(){
        try{
            int i = jTable.getSelectedRow();
            if(i>=0){
                usuarioSelecionado = arrayList.get(i);
                lblUsuario.setText(arrayList.get(i).getNome());
                cbbNivel.setSelectedIndex(arrayList.get(i).getTipo());
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.preencherSelectedTable");
        }
    }
    private void preencherTabela(){
        DefaultTableModel model = new DefaultTableModelNaoEditavel();
        TableRowSorter tableSorter = new TableRowSorter(model);
        
        try{
            model.addColumn("Nº");
            model.addColumn("ID");
            model.addColumn("Nome");
            model.addColumn("Nível");
            Object[] linha;
            preencherArrayList();
            
            for(int i = 0; i< arrayList.size(); i++){
                 linha = new Object[4];
                 linha[0] = (i+1);
                 linha[1] = (arrayList.get(i).getId());
                 linha[2] = (arrayList.get(i).getNome());
                 linha[3] = (arrayList.get(i).getTipoDescricao());
                 model.addRow(linha);
            }
            tableSorter = new TableRowSorter(model);
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.preencherTabela");
        }finally{
            jTable.setModel(model);
            jTable.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable.setRowSorter(tableSorter);
            tableSorter.toggleSortOrder(0);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ckAdmin = new javax.swing.JCheckBox();
        ckOpera = new javax.swing.JCheckBox();
        ckVisua = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbNivel = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfUsuarioNovo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbNivelNovo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txfSenhaNovo = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txfSenhaConfir = new javax.swing.JPasswordField();
        btnInserir = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Usuários");
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10), new java.awt.Color(127, 127, 127))); // NOI18N

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        ckAdmin.setBackground(new java.awt.Color(255, 255, 255));
        ckAdmin.setText("Administrador");
        ckAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckAdminStateChanged(evt);
            }
        });
        jPanel3.add(ckAdmin);

        ckOpera.setBackground(new java.awt.Color(255, 255, 255));
        ckOpera.setText("Operação");
        ckOpera.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckOperaStateChanged(evt);
            }
        });
        jPanel3.add(ckOpera);

        ckVisua.setBackground(new java.awt.Color(255, 255, 255));
        ckVisua.setText("Visualização");
        ckVisua.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckVisuaStateChanged(evt);
            }
        });
        jPanel3.add(ckVisua);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes Selecionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10), new java.awt.Color(127, 127, 127))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Usuário ");
        jPanel1.add(jLabel2);

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("MARIO");
        jPanel1.add(lblUsuario);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Nível");
        jPanel1.add(jLabel4);

        cbbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbbNivel);

        btnExcluir.setBackground(new java.awt.Color(255, 64, 129));
        btnExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 0));
        btnAlterar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir)
                        .addComponent(btnAlterar)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10), new java.awt.Color(127, 127, 127))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.setForeground(new java.awt.Color(127, 127, 127));
        jPanel6.setLayout(new java.awt.GridLayout(2, 6, 5, 5));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Usuário ");
        jPanel6.add(jLabel3);
        jPanel6.add(txfUsuarioNovo);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Nível");
        jPanel6.add(jLabel5);

        cbbNivelNovo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(cbbNivelNovo);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Senha");
        jPanel6.add(jLabel6);
        jPanel6.add(txfSenhaNovo);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Confirmar Senha");
        jPanel6.add(jLabel7);
        jPanel6.add(txfSenhaConfir);

        btnInserir.setBackground(new java.awt.Color(33, 150, 243));
        btnInserir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        lblInfo.setForeground(new java.awt.Color(255, 51, 0));
        lblInfo.setText("Senhas divergem!");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       try{
            int i = usuarioSelecionado.getId();
            if(i>0){
                Thread t = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        usuarioSelecionado.setTipo(cbbNivel.getSelectedIndex());
                        uCtrol.alterarUsuario(usuarioSelecionado);
                        preencherTabela();
                    }});
                t.start();
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.btnAlterarActionPerformed");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try{
            if(uCtrol.excluirUsuario(usuarioSelecionado)){
                preencherTabela();
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "btnExcluirActionPerformed");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void ckAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckAdminStateChanged
        preencherTabela();
    }//GEN-LAST:event_ckAdminStateChanged

    private void ckOperaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckOperaStateChanged
        preencherTabela();
    }//GEN-LAST:event_ckOperaStateChanged

    private void ckVisuaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckVisuaStateChanged
        preencherTabela();
    }//GEN-LAST:event_ckVisuaStateChanged

    public static void atualizarInfo(String info){
       informacao = info;
    }
    private void setInfo(String info){
        lblInfo.setText(info);
    }
    
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try{
            if(uCtrol.inserirNovo(txfUsuarioNovo.getText(),cbbNivelNovo.getSelectedIndex(), txfSenhaNovo.getPassword(), txfSenhaConfir.getPassword())){
                limparCampos();
            }else{
                lblInfo.setVisible(true);
                setInfo(informacao);
            }
        }catch(Exception e){
            aux.RegistrarLog(e.getMessage(), "jpGerenciarUsuarios.btnInserirActionPerformed");
        }
    }//GEN-LAST:event_btnInserirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbbNivel;
    private javax.swing.JComboBox<String> cbbNivelNovo;
    private javax.swing.JCheckBox ckAdmin;
    private javax.swing.JCheckBox ckOpera;
    private javax.swing.JCheckBox ckVisua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txfSenhaConfir;
    private javax.swing.JPasswordField txfSenhaNovo;
    private javax.swing.JTextField txfUsuarioNovo;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        lblInfo.setVisible(false);
        txfSenhaConfir.setText("");
        txfSenhaNovo.setText("");
        txfUsuarioNovo.setText("");
        preencherTabela();
    }
}
