/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author mario
 */
public class jpImagemConfiguracao extends javax.swing.JPanel {

    int configuracao = -1;
    private static String[] IMAGENS_CONFIGURACAO = {"C:\\Projetos\\Netbeans\\BOB\\src\\icons\\4X2.png",
       // "C:\\Projetos\\Netbeans\\BOB\\src\\icons\\4X4.jpg",
        "C:\\Projetos\\Netbeans\\BOB\\src\\icons\\6X2.png",
        "C:\\Projetos\\Netbeans\\BOB\\src\\icons\\6X4.png",
        "C:\\Projetos\\Netbeans\\BOB\\src\\icons\\8X4.png",
       // "C:\\Projetos\\Netbeans\\BOB\\src\\icons\\2X1.jpg"
    };

    public jpImagemConfiguracao() {
        initComponents();
    }

    public jpImagemConfiguracao(int configuracao) {
        initComponents();
        this.configuracao = configuracao;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        try {
            if (configuracao == -1) {
                return;
            }
            String srcImagem = "";
            switch (configuracao) {
                case 0:
                    srcImagem = IMAGENS_CONFIGURACAO[0];
                    break;
                case 1:
                    srcImagem = IMAGENS_CONFIGURACAO[1];
                    break;
                case 2:
                    srcImagem = IMAGENS_CONFIGURACAO[2];
                    break;
                case 3:
                    srcImagem = IMAGENS_CONFIGURACAO[3];
                    break;
                case 4:
                    srcImagem = IMAGENS_CONFIGURACAO[4];
                    break;
                case 5:
                    srcImagem = IMAGENS_CONFIGURACAO[5];
                    break;
                default:
                    srcImagem = IMAGENS_CONFIGURACAO[0];
                    break;
            }

            //BufferedImage im = ImageIO.read(new File("C:\\Projetos\\Netbeans\\SAAE MARMITEX\\src\\View\\4X2.jpg"));
            BufferedImage im = ImageIO.read(new File(srcImagem));
            g.drawImage(im.getScaledInstance(getWidth(), getHeight(), 0), 0, 0, null);
            //g.drawImage(im.getScaledInstance(100, 50, 0), 0, 0, null);
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
