/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import model.Auxiliar;
import model.LinhaItem;

/**
 *
 * @author mario
 */
public class jpLinha extends javax.swing.JPanel {

    Auxiliar aux;
    public jpLinha(LinhaItem linha) {
        inicializar();
        
        int diffkm = linha.getKmProxima() - linha.getKmAtual();
        String msg = " (Restante)";
        int dias = diffkm / linha.getKmDia();
        dias = (dias>1000) ? 1098 : dias;
        lblData.setText(aux.getDataString(aux.adicionarDias(aux.getDataMilisAtual(), dias)));
        if(diffkm<=0){
            barKm.setForeground(Color.red);
            msg = " (Vencido)";
            lblData.setText(aux.getDataStringAtual());
        }
        
        lblItem.setText(linha.getNome());
        lblKmProx.setText(linha.getKmProxima()+"");
        barKm.setMinimum(linha.getKmTroca());
        barKm.setMaximum(linha.getKmProxima());
        barKm.setValue(linha.getKmAtual());
        barKm.setString((diffkm)+msg);
        barKm.setStringPainted(true);
        validate();
        repaint();
    }

    private void inicializar(){
        initComponents();
        aux = new Auxiliar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItem = new javax.swing.JLabel();
        lblKmProx = new javax.swing.JLabel();
        barKm = new javax.swing.JProgressBar();
        lblData = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout());

        lblItem.setText("FILTRO DE COMBUSTÍVEL");
        add(lblItem);

        lblKmProx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKmProx.setText("5205");
        lblKmProx.setIconTextGap(0);
        add(lblKmProx);

        barKm.setBackground(new java.awt.Color(255, 255, 255));
        barKm.setForeground(new java.awt.Color(0, 153, 0));
        barKm.setValue(50);
        barKm.setStringPainted(true);
        add(barKm);

        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("15/12/2020");
        lblData.setIconTextGap(0);
        add(lblData);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barKm;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblKmProx;
    // End of variables declaration//GEN-END:variables
}
