package view;

import model.Pneu;

/**
 *
 * @author mario
 */
public class jpPneu extends javax.swing.JPanel {

    private Pneu pneu;
    private int posicao=0;
    public jpPneu() {
        initComponents();
    }
    private void inicializar(){
        initComponents();
        pneu = new Pneu();
    }
    public jpPneu(Pneu pneu, int posicao){
        inicializar();
        this.pneu = pneu;
        this.posicao = posicao;
        preencherCampos();
    }
    private void preencherCampos(){
        lblFogo.setText(pneu.getFogo()+"");
        lblPosicao.setText(posicao+"");
        lblMarca.setText(pneu.getMarca());
        lblModelo.setText(pneu.getModelo());
        
    }
    public int getPosicao(){
        return posicao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblPosicao = new javax.swing.JLabel();
        lblFogo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(93, 65));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        jLabel3.setText("Posicão");

        lblPosicao.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        lblPosicao.setForeground(new java.awt.Color(255, 51, 153));
        lblPosicao.setText("1");

        lblFogo.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        lblFogo.setForeground(new java.awt.Color(33, 150, 243));
        lblFogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pneu.png"))); // NOI18N
        lblFogo.setText("0");
        lblFogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFogo.setIconTextGap(2);
        lblFogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblMarca.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        lblMarca.setText("Marca");

        lblModelo.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        lblModelo.setText("Modelo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPosicao))
                    .addComponent(lblMarca)
                    .addComponent(lblModelo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFogo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblFogo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPosicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModelo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        revalidate();
        repaint();
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFogo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPosicao;
    // End of variables declaration//GEN-END:variables
}
