package view;

import control.PneuDesgasteControl;
import control.PneuPosicaoControl;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import model.Auxiliar;
import model.Pneu;
import model.PneuPosicao;
import model.Veiculo;

/**
 *
 * @author mario
 */
public class jpPneu extends javax.swing.JPanel {

    private Pneu pneu;
    private int posicao = 0;
    private Veiculo veiculo;
    Auxiliar aux;
    ExecutorService gerenciadorThreads;
    private static String INDISPONIVEL = "Pneu Indisponível";
    private static String SELECAO_INVALIDA = "Selecione um pneu do estoque";
    private boolean invalido = false;
    public jpPneu() {
        initComponents();
    }

    private void inicializar() {
        initComponents();
        pneu = new Pneu();
        aux = new Auxiliar();
        gerenciadorThreads = Executors.newCachedThreadPool();
    }

    public jpPneu(Pneu pneu, Veiculo veiculo, int posicao) {
        inicializar();
        this.pneu = pneu;
        this.posicao = posicao;
        this.veiculo = veiculo;

        preencherCampos();
        calcularCusto();
    }
     public jpPneu(Pneu pneu, Veiculo veiculo, int posicao, boolean invalido) {
        inicializar();
        this.pneu = pneu;
        this.posicao = posicao;
        this.veiculo = veiculo;
        this.invalido = invalido;

        preencherCampos();
        calcularCusto();
    }

    private void preencherCampos() {
        Thread t = new Thread(() -> {
            lblPosicao.setText((posicao + 1) + "");
            if (!invalido) {
                lblFogo.setText(pneu.getFogo() + "");
                lblMarca.setText(pneu.getMarca());
                lblModelo.setText(pneu.getModelo());
            } else {
                lblMarca.setText(INDISPONIVEL +" ("+ pneu.getStatusString()+")");
                lblModelo.setText(SELECAO_INVALIDA);
                lblFogo.setText("");
                
            }
        });
        gerenciadorThreads.execute(t);

    }

    public int getPosicao() {
        return posicao;
    }

    private void calcularCusto() {
        Thread t = new Thread(() -> {
            float custo = 0;
            custo = new PneuDesgasteControl().getCustoDesgasteByIdVeiculoByPosicao(veiculo.getId(), posicao);
            lblCusto.setText(aux.StringFloatReais(custo));
        });
        gerenciadorThreads.execute(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPosicao = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblFogo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(200, 50));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 50));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        lblPosicao.setBackground(new java.awt.Color(255, 255, 255));
        lblPosicao.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblPosicao.setForeground(new java.awt.Color(255, 0, 0));
        lblPosicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosicao.setText("14");
        lblPosicao.setToolTipText("POSIÇÃO");
        lblPosicao.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblPosicao.setOpaque(true);

        jSeparator2.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblFogo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblFogo.setForeground(new java.awt.Color(33, 150, 243));
        lblFogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pneu.png"))); // NOI18N
        lblFogo.setText("1500");
        lblFogo.setToolTipText("FOGO");
        lblFogo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblFogo.setIconTextGap(0);
        lblFogo.setMaximumSize(new java.awt.Dimension(500, 500));
        lblFogo.setMinimumSize(new java.awt.Dimension(0, 0));
        lblFogo.setOpaque(true);
        lblFogo.setPreferredSize(new java.awt.Dimension(0, 0));

        lblMarca.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(51, 51, 51));
        lblMarca.setText("Marca");
        lblMarca.setOpaque(true);

        lblModelo.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(51, 51, 51));
        lblModelo.setText("Modelo");
        lblModelo.setOpaque(true);

        lblCusto.setFont(new java.awt.Font("Times New Roman", 1, 9)); // NOI18N
        lblCusto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCusto.setText("R$ 0000,30 / km");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("...");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setMaximumSize(new java.awt.Dimension(30, 18));
        jButton1.setMinimumSize(new java.awt.Dimension(30, 18));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 18));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPosicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCusto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosicao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMarca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelo))
                        .addComponent(lblFogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        revalidate();
        repaint();
    }//GEN-LAST:event_formComponentResized

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new jdHistoricoPneuPosicao(veiculo, posicao).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblFogo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPosicao;
    // End of variables declaration//GEN-END:variables
}
